services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-esus-1.0
    restart: always
    env_file: .env    
    ports:
      - "3000:3000"
    command: npm run dev